/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ludo;

import core.Fichas.Colores;
import core.Jugador;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Fabian Graterol
 */
public class TurnoJugador extends javax.swing.JFrame {

    Jugador jugador;
    int dado;
    int fichaSeleccionada = 0;
    /**
     * Creates new form TurnoJugador
     */
    public TurnoJugador() {
        initComponents();
    }
    
    public TurnoJugador(Jugador jugador) {
        initComponents();
        this.liberarFicha.setEnabled(false);
        this.moverButton.setEnabled(false);
        this.lanzarbutton.setEnabled(true);
        this.jugador = jugador;
        this.nombreLbael.setText(jugador.getUsername());
        String url = this.jugador.getColor();
        setButtonsIcons(url);
        setFichasEnabled();    

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lanzarbutton = new javax.swing.JButton();
        liberarFicha = new javax.swing.JButton();
        moverButton = new javax.swing.JButton();
        jugadorLabel = new javax.swing.JLabel();
        nombreLbael = new javax.swing.JLabel();
        dadoLabel = new javax.swing.JLabel();
        resultadoLabel = new javax.swing.JLabel();
        terminarButton = new javax.swing.JButton();
        fichaButton1 = new javax.swing.JButton();
        fichaButton2 = new javax.swing.JButton();
        fichaButton3 = new javax.swing.JButton();
        fichaButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lanzarbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dados.png"))); // NOI18N
        lanzarbutton.setText("Lanzar");
        lanzarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanzarbuttonActionPerformed(evt);
            }
        });

        liberarFicha.setText("Liberar Ficha");
        liberarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liberarFichaActionPerformed(evt);
            }
        });

        moverButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MoverPieza.png"))); // NOI18N
        moverButton.setText("Mover");
        moverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moverButtonActionPerformed(evt);
            }
        });

        jugadorLabel.setText("Jugador: ");

        dadoLabel.setText("Dado:");

        resultadoLabel.setText("   ");

        terminarButton.setText("terminar turno");
        terminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarButtonActionPerformed(evt);
            }
        });

        fichaButton1.setText("Ficha 1");
        fichaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichaButton1ActionPerformed(evt);
            }
        });

        fichaButton2.setText("Ficha 2");
        fichaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichaButton2ActionPerformed(evt);
            }
        });

        fichaButton3.setText("Ficha 3");
        fichaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichaButton3ActionPerformed(evt);
            }
        });

        fichaButton4.setText("Ficha 4");
        fichaButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichaButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fichaButton1)
                        .addGap(18, 18, 18)
                        .addComponent(fichaButton2)
                        .addGap(18, 18, 18)
                        .addComponent(fichaButton3)
                        .addGap(18, 18, 18)
                        .addComponent(fichaButton4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(terminarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(liberarFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lanzarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jugadorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreLbael)
                        .addGap(55, 55, 55)
                        .addComponent(dadoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultadoLabel)))
                .addGap(291, 291, 291))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jugadorLabel)
                            .addComponent(nombreLbael)
                            .addComponent(dadoLabel)
                            .addComponent(resultadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fichaButton1)
                            .addComponent(fichaButton2)
                            .addComponent(fichaButton3)
                            .addComponent(fichaButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lanzarbutton)
                        .addGap(18, 18, 18)
                        .addComponent(moverButton)
                        .addGap(18, 18, 18)
                        .addComponent(liberarFicha)
                        .addGap(18, 18, 18)
                        .addComponent(terminarButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lanzarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanzarbuttonActionPerformed
        dado = jugador.lanzarDado();
        this.resultadoLabel.setText(Integer.toString(dado));
        if (dado == 6){
            this.liberarFicha.setEnabled(true);
            if (!this.jugador.getFichaInMeta(0)){this.fichaButton1.setEnabled(true);}
            if (!this.jugador.getFichaInMeta(1)){this.fichaButton2.setEnabled(true);}
            if (!this.jugador.getFichaInMeta(2)){this.fichaButton3.setEnabled(true);}
            if (!this.jugador.getFichaInMeta(3)){this.fichaButton4.setEnabled(true);}
        } else if (this.jugador.puedeMoverFicha()){
            this.moverButton.setEnabled(true);
            setFichasEnabled();
        }
        //this.lanzarbutton.setEnabled(false);
    }//GEN-LAST:event_lanzarbuttonActionPerformed

    private void moverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moverButtonActionPerformed
        if (this.jugador.getFichaInHome(this.fichaSeleccionada)){
            System.out.println("Ficha esta en home");
        } else{
            this.liberarFicha.setEnabled(false);
            this.jugador.moverFicha(this.fichaSeleccionada, this.dado);
            setFichasEnabled();
        }
    }//GEN-LAST:event_moverButtonActionPerformed

    private void fichaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichaButton1ActionPerformed
        this.fichaSeleccionada = 0;
    }//GEN-LAST:event_fichaButton1ActionPerformed

    private void fichaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichaButton2ActionPerformed
        this.fichaSeleccionada = 1;
    }//GEN-LAST:event_fichaButton2ActionPerformed

    private void fichaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichaButton3ActionPerformed
        this.fichaSeleccionada = 2;
    }//GEN-LAST:event_fichaButton3ActionPerformed

    private void fichaButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichaButton4ActionPerformed
        this.fichaSeleccionada = 3;
    }//GEN-LAST:event_fichaButton4ActionPerformed

    private void liberarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liberarFichaActionPerformed
        this.jugador.liberarFicha(this.fichaSeleccionada);
        this.moverButton.setEnabled(false);
        this.liberarFicha.setEnabled(false);
        this.lanzarbutton.setEnabled(true);
        setFichasEnabled();
    }//GEN-LAST:event_liberarFichaActionPerformed

    private void terminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarButtonActionPerformed
        setFichasEnabled();
    }//GEN-LAST:event_terminarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TurnoJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TurnoJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TurnoJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TurnoJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TurnoJugador().setVisible(true);
            }
        });
    }
    
    private void setFichasEnabled(){
        if (!this.jugador.getFichaInMeta(0)){
            this.fichaButton1.setEnabled(!this.jugador.getFichaInHome(0));
        }
        else {
            this.fichaButton1.setEnabled(false);
        }
        if (!this.jugador.getFichaInMeta(1)){this.fichaButton2.setEnabled(
                !this.jugador.getFichaInHome(1));
        }
        else {
            this.fichaButton2.setEnabled(false);
        }
        if (!this.jugador.getFichaInMeta(2)){
            this.fichaButton3.setEnabled(!this.jugador.getFichaInHome(2));
        }
        else {
            this.fichaButton3.setEnabled(false);
        }
        if (!this.jugador.getFichaInMeta(3)){
            this.fichaButton4.setEnabled(!this.jugador.getFichaInHome(3));
        }
        else {
            this.fichaButton4.setEnabled(false);
        }
        
        
        
        
    }
    
    private void setButtonsIcons(String name){
        Image img;
        try {
            ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
            InputStream input = classLoader.getResourceAsStream("assets/"+name);
            BufferedImage image = ImageIO.read(input);
            this.fichaButton1.setIcon(new ImageIcon(image));
            this.fichaButton2.setIcon(new ImageIcon(image));
            this.fichaButton3.setIcon(new ImageIcon(image));
            this.fichaButton4.setIcon(new ImageIcon(image));

        } catch (IOException ex) {
            Logger.getLogger(TurnoJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dadoLabel;
    private javax.swing.JButton fichaButton1;
    private javax.swing.JButton fichaButton2;
    private javax.swing.JButton fichaButton3;
    private javax.swing.JButton fichaButton4;
    private javax.swing.JLabel jugadorLabel;
    private javax.swing.JButton lanzarbutton;
    private javax.swing.JButton liberarFicha;
    private javax.swing.JButton moverButton;
    private javax.swing.JLabel nombreLbael;
    private javax.swing.JLabel resultadoLabel;
    private javax.swing.JButton terminarButton;
    // End of variables declaration//GEN-END:variables
}
